//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaiServiceSOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com", ConfigurationName="EaiServiceSOAP.IntegrationEntry")]
    public interface IntegrationEntry
    {
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.invokeSrvResponse invokeSrv(EaiServiceSOAP.invokeSrvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeSrvResponse> invokeSrvAsync(EaiServiceSOAP.invokeSrvRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.regEAIResponse regEAI(EaiServiceSOAP.regEAIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.regEAIResponse> regEAIAsync(EaiServiceSOAP.regEAIRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.regSrvResponse regSrv(EaiServiceSOAP.regSrvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.regSrvResponse> regSrvAsync(EaiServiceSOAP.regSrvRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 getParamListReturn 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getParamListResponse getParamList(EaiServiceSOAP.getParamListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getParamListResponse> getParamListAsync(EaiServiceSOAP.getParamListRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 getStandardServiceListReturn 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getStandardServiceListResponse getStandardServiceList(EaiServiceSOAP.getStandardServiceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getStandardServiceListResponse> getStandardServiceListAsync(EaiServiceSOAP.getStandardServiceListRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 getStandardDataNameListReturn 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getStandardDataNameListResponse getStandardDataNameList(EaiServiceSOAP.getStandardDataNameListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getStandardDataNameListResponse> getStandardDataNameListAsync(EaiServiceSOAP.getStandardDataNameListRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getSrvResponse getSrv(EaiServiceSOAP.getSrvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getSrvResponse> getSrvAsync(EaiServiceSOAP.getSrvRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 getProdListReturn 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getProdListResponse getProdList(EaiServiceSOAP.getProdListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getProdListResponse> getProdListAsync(EaiServiceSOAP.getProdListRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.invokeMdmResponse invokeMdm(EaiServiceSOAP.invokeMdmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeMdmResponse> invokeMdmAsync(EaiServiceSOAP.invokeMdmRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getProdResponse getProd(EaiServiceSOAP.getProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getProdResponse> getProdAsync(EaiServiceSOAP.getProdRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.fpInvokeResponse fpInvoke(EaiServiceSOAP.fpInvokeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.fpInvokeResponse> fpInvokeAsync(EaiServiceSOAP.fpInvokeRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.regProdAPResponse regProdAP(EaiServiceSOAP.regProdAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.regProdAPResponse> regProdAPAsync(EaiServiceSOAP.regProdAPRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.invokeEtlResponse invokeEtl(EaiServiceSOAP.invokeEtlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeEtlResponse> invokeEtlAsync(EaiServiceSOAP.invokeEtlRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.getEtlJobListResponse getEtlJobList(EaiServiceSOAP.getEtlJobListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.getEtlJobListResponse> getEtlJobListAsync(EaiServiceSOAP.getEtlJobListRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.escrowResendSrvResponse escrowResendSrv(EaiServiceSOAP.escrowResendSrvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.escrowResendSrvResponse> escrowResendSrvAsync(EaiServiceSOAP.escrowResendSrvRequest request);
        
        // CODEGEN: 因為命名空間 http://entry.serviceengine.cross.digiwin.com 的元素名稱 in0 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EaiServiceSOAP.invokeUnionResponse invokeUnion(EaiServiceSOAP.invokeUnionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeUnionResponse> invokeUnionAsync(EaiServiceSOAP.invokeUnionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSrvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSrv", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeSrvRequestBody Body;
        
        public invokeSrvRequest()
        {
        }
        
        public invokeSrvRequest(EaiServiceSOAP.invokeSrvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeSrvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public invokeSrvRequestBody()
        {
        }
        
        public invokeSrvRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSrvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSrvResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeSrvResponseBody Body;
        
        public invokeSrvResponse()
        {
        }
        
        public invokeSrvResponse(EaiServiceSOAP.invokeSrvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeSrvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invokeSrvReturn;
        
        public invokeSrvResponseBody()
        {
        }
        
        public invokeSrvResponseBody(string invokeSrvReturn)
        {
            this.invokeSrvReturn = invokeSrvReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class regEAIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="regEAI", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.regEAIRequestBody Body;
        
        public regEAIRequest()
        {
        }
        
        public regEAIRequest(EaiServiceSOAP.regEAIRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class regEAIRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public regEAIRequestBody()
        {
        }
        
        public regEAIRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class regEAIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="regEAIResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.regEAIResponseBody Body;
        
        public regEAIResponse()
        {
        }
        
        public regEAIResponse(EaiServiceSOAP.regEAIResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class regEAIResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regEAIReturn;
        
        public regEAIResponseBody()
        {
        }
        
        public regEAIResponseBody(string regEAIReturn)
        {
            this.regEAIReturn = regEAIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class regSrvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="regSrv", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.regSrvRequestBody Body;
        
        public regSrvRequest()
        {
        }
        
        public regSrvRequest(EaiServiceSOAP.regSrvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class regSrvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public regSrvRequestBody()
        {
        }
        
        public regSrvRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class regSrvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="regSrvResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.regSrvResponseBody Body;
        
        public regSrvResponse()
        {
        }
        
        public regSrvResponse(EaiServiceSOAP.regSrvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class regSrvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regSrvReturn;
        
        public regSrvResponseBody()
        {
        }
        
        public regSrvResponseBody(string regSrvReturn)
        {
            this.regSrvReturn = regSrvReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParamListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParamList", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getParamListRequestBody Body;
        
        public getParamListRequest()
        {
        }
        
        public getParamListRequest(EaiServiceSOAP.getParamListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getParamListRequestBody
    {
        
        public getParamListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParamListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParamListResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getParamListResponseBody Body;
        
        public getParamListResponse()
        {
        }
        
        public getParamListResponse(EaiServiceSOAP.getParamListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getParamListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getParamListReturn;
        
        public getParamListResponseBody()
        {
        }
        
        public getParamListResponseBody(string getParamListReturn)
        {
            this.getParamListReturn = getParamListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStandardServiceListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStandardServiceList", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getStandardServiceListRequestBody Body;
        
        public getStandardServiceListRequest()
        {
        }
        
        public getStandardServiceListRequest(EaiServiceSOAP.getStandardServiceListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getStandardServiceListRequestBody
    {
        
        public getStandardServiceListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStandardServiceListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStandardServiceListResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getStandardServiceListResponseBody Body;
        
        public getStandardServiceListResponse()
        {
        }
        
        public getStandardServiceListResponse(EaiServiceSOAP.getStandardServiceListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getStandardServiceListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getStandardServiceListReturn;
        
        public getStandardServiceListResponseBody()
        {
        }
        
        public getStandardServiceListResponseBody(string getStandardServiceListReturn)
        {
            this.getStandardServiceListReturn = getStandardServiceListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStandardDataNameListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStandardDataNameList", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getStandardDataNameListRequestBody Body;
        
        public getStandardDataNameListRequest()
        {
        }
        
        public getStandardDataNameListRequest(EaiServiceSOAP.getStandardDataNameListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getStandardDataNameListRequestBody
    {
        
        public getStandardDataNameListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStandardDataNameListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStandardDataNameListResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getStandardDataNameListResponseBody Body;
        
        public getStandardDataNameListResponse()
        {
        }
        
        public getStandardDataNameListResponse(EaiServiceSOAP.getStandardDataNameListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getStandardDataNameListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getStandardDataNameListReturn;
        
        public getStandardDataNameListResponseBody()
        {
        }
        
        public getStandardDataNameListResponseBody(string getStandardDataNameListReturn)
        {
            this.getStandardDataNameListReturn = getStandardDataNameListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSrvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSrv", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getSrvRequestBody Body;
        
        public getSrvRequest()
        {
        }
        
        public getSrvRequest(EaiServiceSOAP.getSrvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getSrvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getSrvRequestBody()
        {
        }
        
        public getSrvRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSrvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSrvResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getSrvResponseBody Body;
        
        public getSrvResponse()
        {
        }
        
        public getSrvResponse(EaiServiceSOAP.getSrvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getSrvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSrvReturn;
        
        public getSrvResponseBody()
        {
        }
        
        public getSrvResponseBody(string getSrvReturn)
        {
            this.getSrvReturn = getSrvReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdList", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getProdListRequestBody Body;
        
        public getProdListRequest()
        {
        }
        
        public getProdListRequest(EaiServiceSOAP.getProdListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getProdListRequestBody
    {
        
        public getProdListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdListResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getProdListResponseBody Body;
        
        public getProdListResponse()
        {
        }
        
        public getProdListResponse(EaiServiceSOAP.getProdListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getProdListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProdListReturn;
        
        public getProdListResponseBody()
        {
        }
        
        public getProdListResponseBody(string getProdListReturn)
        {
            this.getProdListReturn = getProdListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeMdmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeMdm", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeMdmRequestBody Body;
        
        public invokeMdmRequest()
        {
        }
        
        public invokeMdmRequest(EaiServiceSOAP.invokeMdmRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeMdmRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public invokeMdmRequestBody()
        {
        }
        
        public invokeMdmRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeMdmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeMdmResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeMdmResponseBody Body;
        
        public invokeMdmResponse()
        {
        }
        
        public invokeMdmResponse(EaiServiceSOAP.invokeMdmResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeMdmResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invokeMdmReturn;
        
        public invokeMdmResponseBody()
        {
        }
        
        public invokeMdmResponseBody(string invokeMdmReturn)
        {
            this.invokeMdmReturn = invokeMdmReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProd", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getProdRequestBody Body;
        
        public getProdRequest()
        {
        }
        
        public getProdRequest(EaiServiceSOAP.getProdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getProdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getProdRequestBody()
        {
        }
        
        public getProdRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getProdResponseBody Body;
        
        public getProdResponse()
        {
        }
        
        public getProdResponse(EaiServiceSOAP.getProdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getProdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProdReturn;
        
        public getProdResponseBody()
        {
        }
        
        public getProdResponseBody(string getProdReturn)
        {
            this.getProdReturn = getProdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fpInvokeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fpInvoke", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.fpInvokeRequestBody Body;
        
        public fpInvokeRequest()
        {
        }
        
        public fpInvokeRequest(EaiServiceSOAP.fpInvokeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class fpInvokeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public fpInvokeRequestBody()
        {
        }
        
        public fpInvokeRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fpInvokeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fpInvokeResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.fpInvokeResponseBody Body;
        
        public fpInvokeResponse()
        {
        }
        
        public fpInvokeResponse(EaiServiceSOAP.fpInvokeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class fpInvokeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fpInvokeReturn;
        
        public fpInvokeResponseBody()
        {
        }
        
        public fpInvokeResponseBody(string fpInvokeReturn)
        {
            this.fpInvokeReturn = fpInvokeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class regProdAPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="regProdAP", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.regProdAPRequestBody Body;
        
        public regProdAPRequest()
        {
        }
        
        public regProdAPRequest(EaiServiceSOAP.regProdAPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class regProdAPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public regProdAPRequestBody()
        {
        }
        
        public regProdAPRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class regProdAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="regProdAPResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.regProdAPResponseBody Body;
        
        public regProdAPResponse()
        {
        }
        
        public regProdAPResponse(EaiServiceSOAP.regProdAPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class regProdAPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regProdAPReturn;
        
        public regProdAPResponseBody()
        {
        }
        
        public regProdAPResponseBody(string regProdAPReturn)
        {
            this.regProdAPReturn = regProdAPReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeEtlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeEtl", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeEtlRequestBody Body;
        
        public invokeEtlRequest()
        {
        }
        
        public invokeEtlRequest(EaiServiceSOAP.invokeEtlRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeEtlRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public invokeEtlRequestBody()
        {
        }
        
        public invokeEtlRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeEtlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeEtlResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeEtlResponseBody Body;
        
        public invokeEtlResponse()
        {
        }
        
        public invokeEtlResponse(EaiServiceSOAP.invokeEtlResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeEtlResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invokeEtlReturn;
        
        public invokeEtlResponseBody()
        {
        }
        
        public invokeEtlResponseBody(string invokeEtlReturn)
        {
            this.invokeEtlReturn = invokeEtlReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEtlJobListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEtlJobList", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getEtlJobListRequestBody Body;
        
        public getEtlJobListRequest()
        {
        }
        
        public getEtlJobListRequest(EaiServiceSOAP.getEtlJobListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getEtlJobListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getEtlJobListRequestBody()
        {
        }
        
        public getEtlJobListRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEtlJobListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEtlJobListResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.getEtlJobListResponseBody Body;
        
        public getEtlJobListResponse()
        {
        }
        
        public getEtlJobListResponse(EaiServiceSOAP.getEtlJobListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class getEtlJobListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEtlJobListReturn;
        
        public getEtlJobListResponseBody()
        {
        }
        
        public getEtlJobListResponseBody(string getEtlJobListReturn)
        {
            this.getEtlJobListReturn = getEtlJobListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escrowResendSrvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escrowResendSrv", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.escrowResendSrvRequestBody Body;
        
        public escrowResendSrvRequest()
        {
        }
        
        public escrowResendSrvRequest(EaiServiceSOAP.escrowResendSrvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class escrowResendSrvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public escrowResendSrvRequestBody()
        {
        }
        
        public escrowResendSrvRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escrowResendSrvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escrowResendSrvResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.escrowResendSrvResponseBody Body;
        
        public escrowResendSrvResponse()
        {
        }
        
        public escrowResendSrvResponse(EaiServiceSOAP.escrowResendSrvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class escrowResendSrvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string escrowResendSrvReturn;
        
        public escrowResendSrvResponseBody()
        {
        }
        
        public escrowResendSrvResponseBody(string escrowResendSrvReturn)
        {
            this.escrowResendSrvReturn = escrowResendSrvReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeUnionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeUnion", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeUnionRequestBody Body;
        
        public invokeUnionRequest()
        {
        }
        
        public invokeUnionRequest(EaiServiceSOAP.invokeUnionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeUnionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public invokeUnionRequestBody()
        {
        }
        
        public invokeUnionRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeUnionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeUnionResponse", Namespace="http://entry.serviceengine.cross.digiwin.com", Order=0)]
        public EaiServiceSOAP.invokeUnionResponseBody Body;
        
        public invokeUnionResponse()
        {
        }
        
        public invokeUnionResponse(EaiServiceSOAP.invokeUnionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://entry.serviceengine.cross.digiwin.com")]
    public partial class invokeUnionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invokeUnionReturn;
        
        public invokeUnionResponseBody()
        {
        }
        
        public invokeUnionResponseBody(string invokeUnionReturn)
        {
            this.invokeUnionReturn = invokeUnionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IntegrationEntryChannel : EaiServiceSOAP.IntegrationEntry, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class IntegrationEntryClient : System.ServiceModel.ClientBase<EaiServiceSOAP.IntegrationEntry>, EaiServiceSOAP.IntegrationEntry
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IntegrationEntryClient() : 
                base(IntegrationEntryClient.GetDefaultBinding(), IntegrationEntryClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IntegrationEntry.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationEntryClient(EndpointConfiguration endpointConfiguration) : 
                base(IntegrationEntryClient.GetBindingForEndpoint(endpointConfiguration), IntegrationEntryClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationEntryClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IntegrationEntryClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationEntryClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IntegrationEntryClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationEntryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.invokeSrvResponse EaiServiceSOAP.IntegrationEntry.invokeSrv(EaiServiceSOAP.invokeSrvRequest request)
        {
            return base.Channel.invokeSrv(request);
        }
        
        public string invokeSrv(string in0)
        {
            EaiServiceSOAP.invokeSrvRequest inValue = new EaiServiceSOAP.invokeSrvRequest();
            inValue.Body = new EaiServiceSOAP.invokeSrvRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.invokeSrvResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).invokeSrv(inValue);
            return retVal.Body.invokeSrvReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeSrvResponse> EaiServiceSOAP.IntegrationEntry.invokeSrvAsync(EaiServiceSOAP.invokeSrvRequest request)
        {
            return base.Channel.invokeSrvAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.invokeSrvResponse> invokeSrvAsync(string in0)
        {
            EaiServiceSOAP.invokeSrvRequest inValue = new EaiServiceSOAP.invokeSrvRequest();
            inValue.Body = new EaiServiceSOAP.invokeSrvRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).invokeSrvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.regEAIResponse EaiServiceSOAP.IntegrationEntry.regEAI(EaiServiceSOAP.regEAIRequest request)
        {
            return base.Channel.regEAI(request);
        }
        
        public string regEAI(string in0)
        {
            EaiServiceSOAP.regEAIRequest inValue = new EaiServiceSOAP.regEAIRequest();
            inValue.Body = new EaiServiceSOAP.regEAIRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.regEAIResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).regEAI(inValue);
            return retVal.Body.regEAIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.regEAIResponse> EaiServiceSOAP.IntegrationEntry.regEAIAsync(EaiServiceSOAP.regEAIRequest request)
        {
            return base.Channel.regEAIAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.regEAIResponse> regEAIAsync(string in0)
        {
            EaiServiceSOAP.regEAIRequest inValue = new EaiServiceSOAP.regEAIRequest();
            inValue.Body = new EaiServiceSOAP.regEAIRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).regEAIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.regSrvResponse EaiServiceSOAP.IntegrationEntry.regSrv(EaiServiceSOAP.regSrvRequest request)
        {
            return base.Channel.regSrv(request);
        }
        
        public string regSrv(string in0)
        {
            EaiServiceSOAP.regSrvRequest inValue = new EaiServiceSOAP.regSrvRequest();
            inValue.Body = new EaiServiceSOAP.regSrvRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.regSrvResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).regSrv(inValue);
            return retVal.Body.regSrvReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.regSrvResponse> EaiServiceSOAP.IntegrationEntry.regSrvAsync(EaiServiceSOAP.regSrvRequest request)
        {
            return base.Channel.regSrvAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.regSrvResponse> regSrvAsync(string in0)
        {
            EaiServiceSOAP.regSrvRequest inValue = new EaiServiceSOAP.regSrvRequest();
            inValue.Body = new EaiServiceSOAP.regSrvRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).regSrvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getParamListResponse EaiServiceSOAP.IntegrationEntry.getParamList(EaiServiceSOAP.getParamListRequest request)
        {
            return base.Channel.getParamList(request);
        }
        
        public string getParamList()
        {
            EaiServiceSOAP.getParamListRequest inValue = new EaiServiceSOAP.getParamListRequest();
            inValue.Body = new EaiServiceSOAP.getParamListRequestBody();
            EaiServiceSOAP.getParamListResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getParamList(inValue);
            return retVal.Body.getParamListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getParamListResponse> EaiServiceSOAP.IntegrationEntry.getParamListAsync(EaiServiceSOAP.getParamListRequest request)
        {
            return base.Channel.getParamListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getParamListResponse> getParamListAsync()
        {
            EaiServiceSOAP.getParamListRequest inValue = new EaiServiceSOAP.getParamListRequest();
            inValue.Body = new EaiServiceSOAP.getParamListRequestBody();
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getParamListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getStandardServiceListResponse EaiServiceSOAP.IntegrationEntry.getStandardServiceList(EaiServiceSOAP.getStandardServiceListRequest request)
        {
            return base.Channel.getStandardServiceList(request);
        }
        
        public string getStandardServiceList()
        {
            EaiServiceSOAP.getStandardServiceListRequest inValue = new EaiServiceSOAP.getStandardServiceListRequest();
            inValue.Body = new EaiServiceSOAP.getStandardServiceListRequestBody();
            EaiServiceSOAP.getStandardServiceListResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getStandardServiceList(inValue);
            return retVal.Body.getStandardServiceListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getStandardServiceListResponse> EaiServiceSOAP.IntegrationEntry.getStandardServiceListAsync(EaiServiceSOAP.getStandardServiceListRequest request)
        {
            return base.Channel.getStandardServiceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getStandardServiceListResponse> getStandardServiceListAsync()
        {
            EaiServiceSOAP.getStandardServiceListRequest inValue = new EaiServiceSOAP.getStandardServiceListRequest();
            inValue.Body = new EaiServiceSOAP.getStandardServiceListRequestBody();
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getStandardServiceListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getStandardDataNameListResponse EaiServiceSOAP.IntegrationEntry.getStandardDataNameList(EaiServiceSOAP.getStandardDataNameListRequest request)
        {
            return base.Channel.getStandardDataNameList(request);
        }
        
        public string getStandardDataNameList()
        {
            EaiServiceSOAP.getStandardDataNameListRequest inValue = new EaiServiceSOAP.getStandardDataNameListRequest();
            inValue.Body = new EaiServiceSOAP.getStandardDataNameListRequestBody();
            EaiServiceSOAP.getStandardDataNameListResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getStandardDataNameList(inValue);
            return retVal.Body.getStandardDataNameListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getStandardDataNameListResponse> EaiServiceSOAP.IntegrationEntry.getStandardDataNameListAsync(EaiServiceSOAP.getStandardDataNameListRequest request)
        {
            return base.Channel.getStandardDataNameListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getStandardDataNameListResponse> getStandardDataNameListAsync()
        {
            EaiServiceSOAP.getStandardDataNameListRequest inValue = new EaiServiceSOAP.getStandardDataNameListRequest();
            inValue.Body = new EaiServiceSOAP.getStandardDataNameListRequestBody();
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getStandardDataNameListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getSrvResponse EaiServiceSOAP.IntegrationEntry.getSrv(EaiServiceSOAP.getSrvRequest request)
        {
            return base.Channel.getSrv(request);
        }
        
        public string getSrv(string in0)
        {
            EaiServiceSOAP.getSrvRequest inValue = new EaiServiceSOAP.getSrvRequest();
            inValue.Body = new EaiServiceSOAP.getSrvRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.getSrvResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getSrv(inValue);
            return retVal.Body.getSrvReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getSrvResponse> EaiServiceSOAP.IntegrationEntry.getSrvAsync(EaiServiceSOAP.getSrvRequest request)
        {
            return base.Channel.getSrvAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getSrvResponse> getSrvAsync(string in0)
        {
            EaiServiceSOAP.getSrvRequest inValue = new EaiServiceSOAP.getSrvRequest();
            inValue.Body = new EaiServiceSOAP.getSrvRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getSrvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getProdListResponse EaiServiceSOAP.IntegrationEntry.getProdList(EaiServiceSOAP.getProdListRequest request)
        {
            return base.Channel.getProdList(request);
        }
        
        public string getProdList()
        {
            EaiServiceSOAP.getProdListRequest inValue = new EaiServiceSOAP.getProdListRequest();
            inValue.Body = new EaiServiceSOAP.getProdListRequestBody();
            EaiServiceSOAP.getProdListResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getProdList(inValue);
            return retVal.Body.getProdListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getProdListResponse> EaiServiceSOAP.IntegrationEntry.getProdListAsync(EaiServiceSOAP.getProdListRequest request)
        {
            return base.Channel.getProdListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getProdListResponse> getProdListAsync()
        {
            EaiServiceSOAP.getProdListRequest inValue = new EaiServiceSOAP.getProdListRequest();
            inValue.Body = new EaiServiceSOAP.getProdListRequestBody();
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getProdListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.invokeMdmResponse EaiServiceSOAP.IntegrationEntry.invokeMdm(EaiServiceSOAP.invokeMdmRequest request)
        {
            return base.Channel.invokeMdm(request);
        }
        
        public string invokeMdm(string in0)
        {
            EaiServiceSOAP.invokeMdmRequest inValue = new EaiServiceSOAP.invokeMdmRequest();
            inValue.Body = new EaiServiceSOAP.invokeMdmRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.invokeMdmResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).invokeMdm(inValue);
            return retVal.Body.invokeMdmReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeMdmResponse> EaiServiceSOAP.IntegrationEntry.invokeMdmAsync(EaiServiceSOAP.invokeMdmRequest request)
        {
            return base.Channel.invokeMdmAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.invokeMdmResponse> invokeMdmAsync(string in0)
        {
            EaiServiceSOAP.invokeMdmRequest inValue = new EaiServiceSOAP.invokeMdmRequest();
            inValue.Body = new EaiServiceSOAP.invokeMdmRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).invokeMdmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getProdResponse EaiServiceSOAP.IntegrationEntry.getProd(EaiServiceSOAP.getProdRequest request)
        {
            return base.Channel.getProd(request);
        }
        
        public string getProd(string in0)
        {
            EaiServiceSOAP.getProdRequest inValue = new EaiServiceSOAP.getProdRequest();
            inValue.Body = new EaiServiceSOAP.getProdRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.getProdResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getProd(inValue);
            return retVal.Body.getProdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getProdResponse> EaiServiceSOAP.IntegrationEntry.getProdAsync(EaiServiceSOAP.getProdRequest request)
        {
            return base.Channel.getProdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getProdResponse> getProdAsync(string in0)
        {
            EaiServiceSOAP.getProdRequest inValue = new EaiServiceSOAP.getProdRequest();
            inValue.Body = new EaiServiceSOAP.getProdRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getProdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.fpInvokeResponse EaiServiceSOAP.IntegrationEntry.fpInvoke(EaiServiceSOAP.fpInvokeRequest request)
        {
            return base.Channel.fpInvoke(request);
        }
        
        public string fpInvoke(string in0)
        {
            EaiServiceSOAP.fpInvokeRequest inValue = new EaiServiceSOAP.fpInvokeRequest();
            inValue.Body = new EaiServiceSOAP.fpInvokeRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.fpInvokeResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).fpInvoke(inValue);
            return retVal.Body.fpInvokeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.fpInvokeResponse> EaiServiceSOAP.IntegrationEntry.fpInvokeAsync(EaiServiceSOAP.fpInvokeRequest request)
        {
            return base.Channel.fpInvokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.fpInvokeResponse> fpInvokeAsync(string in0)
        {
            EaiServiceSOAP.fpInvokeRequest inValue = new EaiServiceSOAP.fpInvokeRequest();
            inValue.Body = new EaiServiceSOAP.fpInvokeRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).fpInvokeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.regProdAPResponse EaiServiceSOAP.IntegrationEntry.regProdAP(EaiServiceSOAP.regProdAPRequest request)
        {
            return base.Channel.regProdAP(request);
        }
        
        public string regProdAP(string in0)
        {
            EaiServiceSOAP.regProdAPRequest inValue = new EaiServiceSOAP.regProdAPRequest();
            inValue.Body = new EaiServiceSOAP.regProdAPRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.regProdAPResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).regProdAP(inValue);
            return retVal.Body.regProdAPReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.regProdAPResponse> EaiServiceSOAP.IntegrationEntry.regProdAPAsync(EaiServiceSOAP.regProdAPRequest request)
        {
            return base.Channel.regProdAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.regProdAPResponse> regProdAPAsync(string in0)
        {
            EaiServiceSOAP.regProdAPRequest inValue = new EaiServiceSOAP.regProdAPRequest();
            inValue.Body = new EaiServiceSOAP.regProdAPRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).regProdAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.invokeEtlResponse EaiServiceSOAP.IntegrationEntry.invokeEtl(EaiServiceSOAP.invokeEtlRequest request)
        {
            return base.Channel.invokeEtl(request);
        }
        
        public string invokeEtl(string in0)
        {
            EaiServiceSOAP.invokeEtlRequest inValue = new EaiServiceSOAP.invokeEtlRequest();
            inValue.Body = new EaiServiceSOAP.invokeEtlRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.invokeEtlResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).invokeEtl(inValue);
            return retVal.Body.invokeEtlReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeEtlResponse> EaiServiceSOAP.IntegrationEntry.invokeEtlAsync(EaiServiceSOAP.invokeEtlRequest request)
        {
            return base.Channel.invokeEtlAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.invokeEtlResponse> invokeEtlAsync(string in0)
        {
            EaiServiceSOAP.invokeEtlRequest inValue = new EaiServiceSOAP.invokeEtlRequest();
            inValue.Body = new EaiServiceSOAP.invokeEtlRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).invokeEtlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.getEtlJobListResponse EaiServiceSOAP.IntegrationEntry.getEtlJobList(EaiServiceSOAP.getEtlJobListRequest request)
        {
            return base.Channel.getEtlJobList(request);
        }
        
        public string getEtlJobList(string in0)
        {
            EaiServiceSOAP.getEtlJobListRequest inValue = new EaiServiceSOAP.getEtlJobListRequest();
            inValue.Body = new EaiServiceSOAP.getEtlJobListRequestBody();
            inValue.Body.in0 = in0;
            EaiServiceSOAP.getEtlJobListResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).getEtlJobList(inValue);
            return retVal.Body.getEtlJobListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.getEtlJobListResponse> EaiServiceSOAP.IntegrationEntry.getEtlJobListAsync(EaiServiceSOAP.getEtlJobListRequest request)
        {
            return base.Channel.getEtlJobListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.getEtlJobListResponse> getEtlJobListAsync(string in0)
        {
            EaiServiceSOAP.getEtlJobListRequest inValue = new EaiServiceSOAP.getEtlJobListRequest();
            inValue.Body = new EaiServiceSOAP.getEtlJobListRequestBody();
            inValue.Body.in0 = in0;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).getEtlJobListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.escrowResendSrvResponse EaiServiceSOAP.IntegrationEntry.escrowResendSrv(EaiServiceSOAP.escrowResendSrvRequest request)
        {
            return base.Channel.escrowResendSrv(request);
        }
        
        public string escrowResendSrv(string in0, string in1)
        {
            EaiServiceSOAP.escrowResendSrvRequest inValue = new EaiServiceSOAP.escrowResendSrvRequest();
            inValue.Body = new EaiServiceSOAP.escrowResendSrvRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EaiServiceSOAP.escrowResendSrvResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).escrowResendSrv(inValue);
            return retVal.Body.escrowResendSrvReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.escrowResendSrvResponse> EaiServiceSOAP.IntegrationEntry.escrowResendSrvAsync(EaiServiceSOAP.escrowResendSrvRequest request)
        {
            return base.Channel.escrowResendSrvAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.escrowResendSrvResponse> escrowResendSrvAsync(string in0, string in1)
        {
            EaiServiceSOAP.escrowResendSrvRequest inValue = new EaiServiceSOAP.escrowResendSrvRequest();
            inValue.Body = new EaiServiceSOAP.escrowResendSrvRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).escrowResendSrvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaiServiceSOAP.invokeUnionResponse EaiServiceSOAP.IntegrationEntry.invokeUnion(EaiServiceSOAP.invokeUnionRequest request)
        {
            return base.Channel.invokeUnion(request);
        }
        
        public string invokeUnion(string in0, string in1)
        {
            EaiServiceSOAP.invokeUnionRequest inValue = new EaiServiceSOAP.invokeUnionRequest();
            inValue.Body = new EaiServiceSOAP.invokeUnionRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EaiServiceSOAP.invokeUnionResponse retVal = ((EaiServiceSOAP.IntegrationEntry)(this)).invokeUnion(inValue);
            return retVal.Body.invokeUnionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EaiServiceSOAP.invokeUnionResponse> EaiServiceSOAP.IntegrationEntry.invokeUnionAsync(EaiServiceSOAP.invokeUnionRequest request)
        {
            return base.Channel.invokeUnionAsync(request);
        }
        
        public System.Threading.Tasks.Task<EaiServiceSOAP.invokeUnionResponse> invokeUnionAsync(string in0, string in1)
        {
            EaiServiceSOAP.invokeUnionRequest inValue = new EaiServiceSOAP.invokeUnionRequest();
            inValue.Body = new EaiServiceSOAP.invokeUnionRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EaiServiceSOAP.IntegrationEntry)(this)).invokeUnionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntegrationEntry))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntegrationEntry))
            {
                return new System.ServiceModel.EndpointAddress("http://10.20.86.123:9999/IntegrationEntry");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IntegrationEntryClient.GetBindingForEndpoint(EndpointConfiguration.IntegrationEntry);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IntegrationEntryClient.GetEndpointAddress(EndpointConfiguration.IntegrationEntry);
        }
        
        public enum EndpointConfiguration
        {
            
            IntegrationEntry,
        }
    }
}
