//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesServiceSOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.imestech.com/wsEAI", ConfigurationName="MesServiceSOAP.wsEAISoap")]
    public interface wsEAISoap
    {
        
        // CODEGEN: 因為命名空間 http://www.imestech.com/wsEAI 的元素名稱 InXml 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/invokeSrv", ReplyAction="*")]
        MesServiceSOAP.invokeSrvResponse invokeSrv(MesServiceSOAP.invokeSrvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/invokeSrv", ReplyAction="*")]
        System.Threading.Tasks.Task<MesServiceSOAP.invokeSrvResponse> invokeSrvAsync(MesServiceSOAP.invokeSrvRequest request);
        
        // CODEGEN: 因為命名空間 http://www.imestech.com/wsEAI 的元素名稱 MethodName 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/invokeSrv_ResolvedXML", ReplyAction="*")]
        MesServiceSOAP.invokeSrv_ResolvedXMLResponse invokeSrv_ResolvedXML(MesServiceSOAP.invokeSrv_ResolvedXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/invokeSrv_ResolvedXML", ReplyAction="*")]
        System.Threading.Tasks.Task<MesServiceSOAP.invokeSrv_ResolvedXMLResponse> invokeSrv_ResolvedXMLAsync(MesServiceSOAP.invokeSrv_ResolvedXMLRequest request);
        
        // CODEGEN: 因為命名空間 http://www.imestech.com/wsEAI 的元素名稱 InXml 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/callbackSrv", ReplyAction="*")]
        MesServiceSOAP.callbackSrvResponse callbackSrv(MesServiceSOAP.callbackSrvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/callbackSrv", ReplyAction="*")]
        System.Threading.Tasks.Task<MesServiceSOAP.callbackSrvResponse> callbackSrvAsync(MesServiceSOAP.callbackSrvRequest request);
        
        // CODEGEN: 因為命名空間 http://www.imestech.com/wsEAI 的元素名稱 InXml 未標示為 nillable，所以正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/syncProd", ReplyAction="*")]
        MesServiceSOAP.syncProdResponse syncProd(MesServiceSOAP.syncProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imestech.com/wsEAI/syncProd", ReplyAction="*")]
        System.Threading.Tasks.Task<MesServiceSOAP.syncProdResponse> syncProdAsync(MesServiceSOAP.syncProdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSrvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSrv", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.invokeSrvRequestBody Body;
        
        public invokeSrvRequest()
        {
        }
        
        public invokeSrvRequest(MesServiceSOAP.invokeSrvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class invokeSrvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public invokeSrvRequestBody()
        {
        }
        
        public invokeSrvRequestBody(string InXml)
        {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSrvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSrvResponse", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.invokeSrvResponseBody Body;
        
        public invokeSrvResponse()
        {
        }
        
        public invokeSrvResponse(MesServiceSOAP.invokeSrvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class invokeSrvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invokeSrvResult;
        
        public invokeSrvResponseBody()
        {
        }
        
        public invokeSrvResponseBody(string invokeSrvResult)
        {
            this.invokeSrvResult = invokeSrvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSrv_ResolvedXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSrv_ResolvedXML", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.invokeSrv_ResolvedXMLRequestBody Body;
        
        public invokeSrv_ResolvedXMLRequest()
        {
        }
        
        public invokeSrv_ResolvedXMLRequest(MesServiceSOAP.invokeSrv_ResolvedXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class invokeSrv_ResolvedXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MethodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string InXml;
        
        public invokeSrv_ResolvedXMLRequestBody()
        {
        }
        
        public invokeSrv_ResolvedXMLRequestBody(string MethodName, string InXml)
        {
            this.MethodName = MethodName;
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSrv_ResolvedXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSrv_ResolvedXMLResponse", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.invokeSrv_ResolvedXMLResponseBody Body;
        
        public invokeSrv_ResolvedXMLResponse()
        {
        }
        
        public invokeSrv_ResolvedXMLResponse(MesServiceSOAP.invokeSrv_ResolvedXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class invokeSrv_ResolvedXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invokeSrv_ResolvedXMLResult;
        
        public invokeSrv_ResolvedXMLResponseBody()
        {
        }
        
        public invokeSrv_ResolvedXMLResponseBody(string invokeSrv_ResolvedXMLResult)
        {
            this.invokeSrv_ResolvedXMLResult = invokeSrv_ResolvedXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class callbackSrvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="callbackSrv", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.callbackSrvRequestBody Body;
        
        public callbackSrvRequest()
        {
        }
        
        public callbackSrvRequest(MesServiceSOAP.callbackSrvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class callbackSrvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public callbackSrvRequestBody()
        {
        }
        
        public callbackSrvRequestBody(string InXml)
        {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class callbackSrvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="callbackSrvResponse", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.callbackSrvResponseBody Body;
        
        public callbackSrvResponse()
        {
        }
        
        public callbackSrvResponse(MesServiceSOAP.callbackSrvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class callbackSrvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callbackSrvResult;
        
        public callbackSrvResponseBody()
        {
        }
        
        public callbackSrvResponseBody(string callbackSrvResult)
        {
            this.callbackSrvResult = callbackSrvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncProdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncProd", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.syncProdRequestBody Body;
        
        public syncProdRequest()
        {
        }
        
        public syncProdRequest(MesServiceSOAP.syncProdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class syncProdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public syncProdRequestBody()
        {
        }
        
        public syncProdRequestBody(string InXml)
        {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncProdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncProdResponse", Namespace="http://www.imestech.com/wsEAI", Order=0)]
        public MesServiceSOAP.syncProdResponseBody Body;
        
        public syncProdResponse()
        {
        }
        
        public syncProdResponse(MesServiceSOAP.syncProdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imestech.com/wsEAI")]
    public partial class syncProdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string syncProdResult;
        
        public syncProdResponseBody()
        {
        }
        
        public syncProdResponseBody(string syncProdResult)
        {
            this.syncProdResult = syncProdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsEAISoapChannel : MesServiceSOAP.wsEAISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsEAISoapClient : System.ServiceModel.ClientBase<MesServiceSOAP.wsEAISoap>, MesServiceSOAP.wsEAISoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsEAISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsEAISoapClient.GetBindingForEndpoint(endpointConfiguration), wsEAISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsEAISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsEAISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsEAISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsEAISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsEAISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MesServiceSOAP.invokeSrvResponse MesServiceSOAP.wsEAISoap.invokeSrv(MesServiceSOAP.invokeSrvRequest request)
        {
            return base.Channel.invokeSrv(request);
        }
        
        public string invokeSrv(string InXml)
        {
            MesServiceSOAP.invokeSrvRequest inValue = new MesServiceSOAP.invokeSrvRequest();
            inValue.Body = new MesServiceSOAP.invokeSrvRequestBody();
            inValue.Body.InXml = InXml;
            MesServiceSOAP.invokeSrvResponse retVal = ((MesServiceSOAP.wsEAISoap)(this)).invokeSrv(inValue);
            return retVal.Body.invokeSrvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesServiceSOAP.invokeSrvResponse> MesServiceSOAP.wsEAISoap.invokeSrvAsync(MesServiceSOAP.invokeSrvRequest request)
        {
            return base.Channel.invokeSrvAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesServiceSOAP.invokeSrvResponse> invokeSrvAsync(string InXml)
        {
            MesServiceSOAP.invokeSrvRequest inValue = new MesServiceSOAP.invokeSrvRequest();
            inValue.Body = new MesServiceSOAP.invokeSrvRequestBody();
            inValue.Body.InXml = InXml;
            return ((MesServiceSOAP.wsEAISoap)(this)).invokeSrvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MesServiceSOAP.invokeSrv_ResolvedXMLResponse MesServiceSOAP.wsEAISoap.invokeSrv_ResolvedXML(MesServiceSOAP.invokeSrv_ResolvedXMLRequest request)
        {
            return base.Channel.invokeSrv_ResolvedXML(request);
        }
        
        public string invokeSrv_ResolvedXML(string MethodName, string InXml)
        {
            MesServiceSOAP.invokeSrv_ResolvedXMLRequest inValue = new MesServiceSOAP.invokeSrv_ResolvedXMLRequest();
            inValue.Body = new MesServiceSOAP.invokeSrv_ResolvedXMLRequestBody();
            inValue.Body.MethodName = MethodName;
            inValue.Body.InXml = InXml;
            MesServiceSOAP.invokeSrv_ResolvedXMLResponse retVal = ((MesServiceSOAP.wsEAISoap)(this)).invokeSrv_ResolvedXML(inValue);
            return retVal.Body.invokeSrv_ResolvedXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesServiceSOAP.invokeSrv_ResolvedXMLResponse> MesServiceSOAP.wsEAISoap.invokeSrv_ResolvedXMLAsync(MesServiceSOAP.invokeSrv_ResolvedXMLRequest request)
        {
            return base.Channel.invokeSrv_ResolvedXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesServiceSOAP.invokeSrv_ResolvedXMLResponse> invokeSrv_ResolvedXMLAsync(string MethodName, string InXml)
        {
            MesServiceSOAP.invokeSrv_ResolvedXMLRequest inValue = new MesServiceSOAP.invokeSrv_ResolvedXMLRequest();
            inValue.Body = new MesServiceSOAP.invokeSrv_ResolvedXMLRequestBody();
            inValue.Body.MethodName = MethodName;
            inValue.Body.InXml = InXml;
            return ((MesServiceSOAP.wsEAISoap)(this)).invokeSrv_ResolvedXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MesServiceSOAP.callbackSrvResponse MesServiceSOAP.wsEAISoap.callbackSrv(MesServiceSOAP.callbackSrvRequest request)
        {
            return base.Channel.callbackSrv(request);
        }
        
        public string callbackSrv(string InXml)
        {
            MesServiceSOAP.callbackSrvRequest inValue = new MesServiceSOAP.callbackSrvRequest();
            inValue.Body = new MesServiceSOAP.callbackSrvRequestBody();
            inValue.Body.InXml = InXml;
            MesServiceSOAP.callbackSrvResponse retVal = ((MesServiceSOAP.wsEAISoap)(this)).callbackSrv(inValue);
            return retVal.Body.callbackSrvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesServiceSOAP.callbackSrvResponse> MesServiceSOAP.wsEAISoap.callbackSrvAsync(MesServiceSOAP.callbackSrvRequest request)
        {
            return base.Channel.callbackSrvAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesServiceSOAP.callbackSrvResponse> callbackSrvAsync(string InXml)
        {
            MesServiceSOAP.callbackSrvRequest inValue = new MesServiceSOAP.callbackSrvRequest();
            inValue.Body = new MesServiceSOAP.callbackSrvRequestBody();
            inValue.Body.InXml = InXml;
            return ((MesServiceSOAP.wsEAISoap)(this)).callbackSrvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MesServiceSOAP.syncProdResponse MesServiceSOAP.wsEAISoap.syncProd(MesServiceSOAP.syncProdRequest request)
        {
            return base.Channel.syncProd(request);
        }
        
        public string syncProd(string InXml)
        {
            MesServiceSOAP.syncProdRequest inValue = new MesServiceSOAP.syncProdRequest();
            inValue.Body = new MesServiceSOAP.syncProdRequestBody();
            inValue.Body.InXml = InXml;
            MesServiceSOAP.syncProdResponse retVal = ((MesServiceSOAP.wsEAISoap)(this)).syncProd(inValue);
            return retVal.Body.syncProdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesServiceSOAP.syncProdResponse> MesServiceSOAP.wsEAISoap.syncProdAsync(MesServiceSOAP.syncProdRequest request)
        {
            return base.Channel.syncProdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesServiceSOAP.syncProdResponse> syncProdAsync(string InXml)
        {
            MesServiceSOAP.syncProdRequest inValue = new MesServiceSOAP.syncProdRequest();
            inValue.Body = new MesServiceSOAP.syncProdRequestBody();
            inValue.Body.InXml = InXml;
            return ((MesServiceSOAP.wsEAISoap)(this)).syncProdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsEAISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsEAISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsEAISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.140.139:7018/SMES_Production_MESws_EAI/wsEAI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsEAISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.140.139:7018/SMES_Production_MESws_EAI/wsEAI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsEAISoap,
            
            wsEAISoap12,
        }
    }
}
